sudo: required
services:
  - docker
before_install:
  - docker build -t kluthe/docker-react-educational -f Dockerfile.dev .
script:
  - docker run kluthe/docker-react-educational npm run test -- --coverage  